### ISSUE TITLE
Window is empty

### ISSUE THREAD

**Issue by rvernica** [SimpleMobileTools/Simple-File-Manager#119]
The window is empty and I cannot create folders or files. I gave `root` access to the app but it did not help. Version `2.6.0`

![screenshot_20171104-165223](https://user-images.githubusercontent.com/241185/32410589-a012e1a8-c181-11e7-809b-5c6c717d3391.png)
![screenshot_20171104-165740](https://user-images.githubusercontent.com/241185/32410590-a2753ca2-c181-11e7-942f-982de7415642.png)

**Comment by tibbi** [comment]
Hey, do you mean the root folder is empty? Or nothing shows up?

**Comment by Phoenix1747** [comment]
This might be an issue with Lineage. Had some similar problem with the lineage stock file manager after flashing. No problems with vendor Android on 2 different devices though (Android 7.0).

Maybe it has something to do with Lineage's privacy protection tool, I don't know.

**Comment by rvernica** [comment]
Nothing shows up.

**Comment by tibbi** [comment]
Root handling will be rewritten in 3.2.0, check if is better. You still cannot really do any operations, just hopefully browse the items.

**Comment by tibbi** [comment]
yep, I could reproduce it already on my other rooted device

**Comment by DHosseiny** [comment]
Hi this bug is happen in non-rooted devices I used old version but because I included library code in my project and changed it a lot, so can't update to new version. I don't know what version I used exactly but com.simplemobiletools:commons:2.25.3
is the version of commons dependency.
Is this bug fixed? can you please send a link to fix commit?
