### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by anthologist** [SimpleMobileTools/Simple-File-Manager#22]
I was about to update a translation when I noticed that the <string name="files_count"> is already translated, but the app doesn't use it. Also the "Direct children count" in the app is not available in the strings.

**Comment by tibbi** [comment]
hey, the whole Properties dialog has been exported in a library, so I can easily reuse it in multiple projects without any duplication whatsoever. If you fix the translations at https://github.com/SimpleMobileTools/Simple-File-Properties/tree/master/library/src/main/res , they will be fixed in all apps that use it. Thanks
