### ISSUE TITLE
[BUG] No Root on File Moving Mode

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-File-Manager#337]
I can't move or copy something from Internal Memory or SDCard, to any Root Path.

(example: data/data/org.mozilla.firefox)

In the preview of the folder says "0 items", if I open it, nothing happens.

**Comment by marcdw1289** [comment]
Using File Manager 6.3.7 on CarbonROM (MultiROM secondary), Android 7.1.2, SuperSU, Moto G5 Plus.
With root access turned on I find not much can be done under root (/). All files are 0 bytes, dated December 31 1969. Unable to view some subdirectories.

For instance I wanted to copy/archive some apps installed via F-Droid. I try to go to /data/data/org.fdroid.fdroid/files/ but cannot. Nothing happens when trying to go to any of the subdirs of the fdroid directory. That behavior is across the filesystem, f.i. can't go into /system/addon.d/. If I try to refresh I just get a never ending spinning indicator. Have to back out.
Also, display doesn't always update properly. When I backed out of the fdroid directory the breadcrumb shows that I am in /data/data/ but the listing still shows the contents of the fdroid directory.

Will check on other ROMs and devices.

**Comment by tibbi** [comment]
should be better already
