### ISSUE TITLE
Renaming files leaves a corrupted file with an old name

### ISSUE THREAD

**Issue by Aga-C** [SimpleMobileTools/Simple-File-Manager#544]
Hi,

It's the same bug as reported in Simple Gallery: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2307#issuecomment-998056847. I'm reposting it, because the bug occurs for other file types, not only pictures. It makes the app unusable, since I can't perform a basic operation without creating wrong entries on my device.

As I've investigated, the bug was introduced in a version 6.11.0. Earlier releases were renaming files without issues. 

It's possible to reproduce the issue on an emulator (Android 12). Just rename a file with Simple File Manager and then use the built-in Files app to navigate where the file was.

**Comment by tibbi** [comment]
it works just fine to me, what files are you renaming? Are they on an SD card or internal storage?

**Comment by Aga-C** [comment]
Any files on internal storage. This issue also occurred on my device, where I don't have an SD card.

https://user-images.githubusercontent.com/85929121/147756449-74191124-7792-4322-96a4-cf4035959a02.mp4

**Comment by zurino** [comment]
I'm having this issue as well. I can rename files on my internal s10 drive. But not on my removable external drive.
I'd also love to see the functions bar appear on the bottom of the app. For example, when you long press a file to rename it, if that options bar would appear at the bottom for ease of use/access. Thank you!

**Comment by KryptKode** [comment]
@Aga-C  Please what device is that? Is it running on  Android 12?

**Comment by Aga-C** [comment]
@KryptKode On the video it's an emulator with Android 12, but I've also encountered it on my device with Android 11.

**Comment by whats-a-diorama** [comment]
Hi. I've recently started having an issue that I suspect is related to this.

If I move a file, I'm unable to open it with anything unless I perform an additional action on the file.

For example, I download an image from my browser. It goes to my Downloads directory. I then move the image to a different directory using Simple File Manager. Simple File Manager shows the image in the new directory and everything appears to be correct, but now I can't open the image with anything. Not even Simple Gallery. (Opening the file in Simple Gallery via Simple File Manager causes Simple Gallery to display the _next_ most recent file in that directory rather than the file I selected.) However, if I then rename the moved file, suddenly I can open it anywhere. And while everything looks as it should in Simple File Manager after I rename it, Simple Gallery (along with other apps) will then show me an additional corrupted file with the old name, as described in this issue.

The additional corrupted file does seem to disappear eventually. I'm not sure exactly when, but I suspect it may be upon reboot.

This is on a Pixel 5a running the latest update of Android 12, if that helps.

Thanks!

**Comment by whats-a-diorama** [comment]
I'm running the latest release from the other day and it looks like the issue with renaming files is resolved! Unfortunately though, I'm still experiencing an issue with moving files.

An easy way that I can recreate it now on my device (Pixel 5a running Android 12 with latest updates) is to take a screenshot, then use Simple File Manager to move the resulting file to a different directory. Simple File Manager will show the file in the new directory, but if I open up Simple Gallery, the image will be gone. However, if I then rename the file in Simple File Manager and reopen Simple Gallery, the file will suddenly appear.

Hope that helps. Thanks for all of your work on this app! It's really great 🙂

**Comment by whats-a-diorama** [comment]
@Aga-C Oh! I hadn't noticed that issue was opened in Simple Gallery a couple days ago.

Admittedly I'm not familiar with the Simple Mobile Tools source, but could an issue in Simple Commons similarly be affecting both apps in this case? I ask because after some further testing, I can recreate this without ever touching Simple Gallery at all.

If I take a screenshot and move it to another directory of images using Simple File Manager, other apps, like the AOSP Gallery, do not see the image either. (Until I do something to the file like renaming it.) However, if I take a screenshot and move it to another directory of images using the AOSP Files app, the image immediately and correctly appears in all apps, including both Simple Gallery and AOSP Gallery.

Whatever happens to be the case, thank you for letting me know about the Simple Gallery issue. I'll follow that one as well 🙂

**Comment by Aga-C** [comment]
Yes, managing files was done in Simple Commons, so it affected those two apps. Simple Commons has functions that involve more than one app.

**Comment by whats-a-diorama** [comment]
In that case, I assume that the resolution of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2360 will probably resolve my issue here. I'll just use the Files app to move screenshots in the meantime, as that's really my only use case where I run into this issue. Simple File Manager has otherwise been great as always!

Thanks for the heads up!
