### ISSUE TITLE
does it really need an integrated pdf viewer?

### ISSUE THREAD

**Issue by notzed** [SimpleMobileTools/Simple-File-Manager#585]
In my opinion adding a pdf viewer somewhat pushes it beyond "simple" for a file manager, plus it creates a package nearly 3x larger and exposes the product to a much much larger security attack surface.

Android is designed so that applications can relatively seamlessly use each other as components so it just doesn't need mega "suite" applications that include the kitchen sink.  Plus there are already very good free pdf and document viewers like mupdf and installing 6.12.3 just added another option when opening a pdf file.

Just from a design perspective I urge you to reconsider including the pdf viewer directly in this particular application, and if you do want to add a pdf viewer as part of the "Simple Tools" instead create a new "Simple Document Viewer" as a separate product?

Anyway this is just a suggestion, ultimately it's up to you.

**Comment by Aga-C** [comment]
I am also for the separate app.
There's already discussion about it:
https://github.com/SimpleMobileTools/General-Discussion/issues/9

**Comment by tibbi** [comment]
Yes, I want to keep it here.

**Comment by esmaeelE** [comment]
Separate PDF reader and release it as new application is a great idea.

**Comment by ToyKeeper** [comment]
Just adding another +1 to the idea of removing the PDF viewer and perhaps making a separate app for "Simple Document Viewer".  It sounds like a nice app for people who haven't already chosen a PDF / ebook reader.  However, for the file manager, I'd rather not have an app which is twice as big as necessary due to a single feature which isn't even related to file management.

So I'm sticking with v6.12.2 for now.  It's the last version before PDF was added, and it doesn't have Bug #594 .

One question though...  In the [discussion](https://github.com/SimpleMobileTools/General-Discussion/issues/9) linked earlier, the plan was to make the document viewer a separate app.  But then it was suddenly added to the file manager instead, and the discussion doesn't show any of the process or reasoning.  Why did the plan change?

**Comment by tibbi** [comment]
well, because I see no other document that needs a separate app. And I definitely dont want to create a standalone pdf viewer.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
But, @tibbi, why do you not want to separate it?

@ToyKeeper provided decent rationale for separation. By what metric is your software simple if it contains irrelevant stuff (that supersedes, which "http://github.com/SimpleMobileTools/Simple-File-Manager/issues/594" demonstrates, what the system attempts to provide)?

**Comment by tibbi** [comment]
a couple MB doesnt matter nowadays... App caches can take up to hundreads of mb.

**Comment by ToyKeeper** [comment]
Yeah, the app size on disk probably doesn't matter.  The size in RAM can make a difference on low-end devices though.

For viewing files, I use different programs for different formats.  Like, Markor for text files, EBookDroid for graphic novels, CoolReader for text books, Dialog Music Player for audio files, Simple Gallery for images, etc.  I can see why someone would want a lightweight pdf viewer too, but it seems like an odd thing to include in a file manager, especially one designed for minimalism.

**Comment by jondo** [comment]
In the light of the security issue #619, this should be reconsidered.

**Comment by Hydroidev** [comment]
I love having the PDF Viewer as an option, but I also agree it should be a separate app so people can choose whether or not they want the added bulk or not.
