### ISSUE TITLE
Please support the open folder intent

### ISSUE THREAD

**Issue by contrapunctus-1** [SimpleMobileTools/Simple-File-Manager#84]
Applications like [Syncthing](https://syncthing.net/) require it to open folders.
See also https://github.com/syncthing/syncthing-android/issues/838

**Comment by k3b** [comment]
goal:

* Intent to open filemanager and view content of a specified directory in the filemanager.
* This feature should not be a picker

my proposal: use this: https://stackoverflow.com/questions/17165972/android-how-to-open-a-specific-folder-via-intent-and-show-its-content-in-a-file
it already works with "EF File Explorer" 

  * action=android.intent.action.VIEW
  * data=file:/path/to/directory/
  * mime=resource/folder

**Comment by tibbi** [comment]
picker and viewer are 2 different things, I will get there someday

**Comment by k3b** [comment]
thanks a lot

**Comment by k3b** [comment]
works great in https://github.com/k3b/APhotoManager/issues/99 . thanks a lot

**Comment by iNPUTmice** [comment]
Can you also support getting the file path from `org.openintents.extra.ABSOLUTE_PATH` as described here: http://www.openintents.org/action/android-intent-action-view/file-directory. Modern Androids (API 24+) do not allow file uris to be transmitted in the data field of an intent. (FileUriExposedException). Should be a 2 line fix. I’m happy to contribute that fix myself if you don’t have any principle objections to handling it that way.

**Comment by tibbi** [comment]
sorry but no, that intent is a custom one belonging to a specific app, not a widely used one

**Comment by iNPUTmice** [comment]
Hi,

I think we can agree that opening a file manager with a specific folder (to
view the content of said folder) is a worthwhile goal and a good feature to
have, right? That's why this issue was resolved in the first place. However
that commit no longer works if the calling application targets API 24. An
app targeting api 24 can not but file:// uris into the data of an intent.
That why my proposal was to put the desired file path into an EXTRA field
instead. If you prefer that I'm happy to call that field
'prg.simplemobiletool.filemanager.extra.path' or what ever. However
openintents is not a vendor specific thing but an attempt to *standardized*
those exact intent that are not covered by basic android.

**Comment by tibbi** [comment]
I will check someday how should it be handled, for now I dont want to add custom intent handling

**Comment by k3b** [comment]
@iNPUTmice 

>  that intent is a custom one belonging to a specific app

I donot like app specific tags, too but at least it is documented which is much more than most other custom tags.

I will add it to my apps as last fallback-try if nothing else works

**Comment by humpity** [comment]
ShareCompat (support.v4) uses setStream(uri) which is really an Intent.ACTION_SEND with a putExtra(Intent.EXTRA_STREAM, uri).
